### ISSUE TITLE
Cannot use Run_If with systems taking Local<LocalStateType>

### ISSUE THREAD

**Issue by Braymatter** [IyesGames/iyes_loopless#29] opened 2022-08-01 20:07 UTC
I would love it if run_if could take Local Arguments in. With the below code I get the following error: 
`        .add_system(self::gamelobby::lobby.run_if(show_lobby_screen))  `

## System: 
```
use super::{UIState, UIStateRes};

pub struct LobbyStateRes{
    pub selected_map: String
}

pub fn lobby(mut egui_context: ResMut<EguiContext>, mut ui_state: ResMut<UIStateRes>, mut maps_manifest: ResMut<MapManifest>, mut lobby_state: Local<LobbyStateRes>) {
    Window::new("Game Lobby")
        .anchor(Align2::CENTER_CENTER, egui::vec2(0.0, -50.0))
        .show(egui_context.ctx_mut(), |ui| {
            egui::ScrollArea::vertical().show(ui, |ui|{
                for map in &maps_manifest.map_files{
                    let sel_map_btn = ui.radio_value(&mut lobby_state.selected_map, map.clone(), map);
                }
            });

            let play_btn = ui.button("Launch Game");

            if play_btn.clicked() && lobby_state.selected_map != *"".to_string(){ //Such unrust shall not stand!
                ui_state.current_state = UIState::Game
            }

            let back_btn = ui.button("Main Menu");

            if back_btn.clicked() {
                ui_state.current_state = UIState::MainMenu;
            }
        });
}
```
## Error
```
[{
	"resource": "/e:/rust/macrophage/src/ui/mod.rs",
	"owner": "rustc",
	"code": {
		"value": "E0599",
		"target": {
			"$mid": 1,
			"external": "https://doc.rust-lang.org/error-index.html#E0599",
			"path": "/error-index.html",
			"scheme": "https",
			"authority": "doc.rust-lang.org",
			"fragment": "E0599"
		}
	},
	"severity": 8,
	"message": "the method `run_if` exists for fn item `for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}`, but its trait bounds were not satisfied\nthe following trait bounds were not satisfied:\n`for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}: bevy::prelude::IntoSystem<(), (), _>`\nwhich is required by `for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}: iyes_loopless::condition::IntoConditionalSystem<_>`\n`&for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}: bevy::prelude::IntoSystem<(), (), _>`\nwhich is required by `&for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}: iyes_loopless::condition::IntoConditionalSystem<_>`\n`&mut for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}: bevy::prelude::IntoSystem<(), (), _>`\nwhich is required by `&mut for<'r, 's, 't0, 't1> fn(bevy::prelude::ResMut<'r, bevy_egui::EguiContext>, bevy::prelude::ResMut<'s, ui::UIStateRes>, bevy::prelude::ResMut<'t0, util::MapManifest>, bevy::prelude::Local<'t1, ui::gamelobby::LobbyStateRes>) {ui::gamelobby::lobby}: iyes_loopless::condition::IntoConditionalSystem<_>`",
	"source": "rustc",
	"startLineNumber": 45,
	"startColumn": 44,
	"endLineNumber": 45,
	"endColumn": 50,
	"relatedInformation": [
		{
			"startLineNumber": 45,
			"startColumn": 21,
			"endLineNumber": 45,
			"endColumn": 43,
			"message": "this is a function, perhaps you wish to call it",
			"resource": "/e:/rust/macrophage/src/ui/mod.rs"
		}
	]
}]

```

**Comment by bmanturner** [comment] 2022-08-23 13:10
You need to give LobbyStateRes a `Default`

**Comment by inodentry** [comment] 2022-10-14 13:48
Closing as "user error".

Bevy requires that types used in `Local` parameters impl `Default`/`FromWorld`. Otherwise your `fn` is not a valid system. The compiler errors unfortunately confusingly point at the library APIs (such as `add_system` or in this case `run_if`), but the problem is not in the libraries.

**Closed by inodentry** 2022-10-14 13:48 UTC
